### ISSUE TITLE
web页面submit的时候报错

### ISSUE THREAD

**Issue by pjcc5** [mMrBun/Chat2BI#19]
报错:

运行的StackTrace
```bash
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Building embedder...
Building corpus...
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/gradio/blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/gradio/utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/projects/Chat2BI/web_demo.py", line 14, in text_analysis
    response_data = function_calling(text, top_k, top_p, temperature, model_type)
  File "/root/autodl-tmp/projects/Chat2BI/core/function_call/build_function_call_pipline.py", line 19, in function_calling
    retrieve_embedder = ToolRetrieverEmbedder(tool_root_dir=tool_root_dir,
  File "/root/autodl-tmp/projects/Chat2BI/retriever/build_retriever.py", line 31, in __init__
    self.corpus, self.corpus2tool = self.build_retrieval_corpus()
  File "/root/autodl-tmp/projects/Chat2BI/retriever/build_retriever.py", line 37, in build_retrieval_corpus
    documents_df = pd.read_csv(self.corpus_tsv_path, sep="\t")
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/root/autodl-tmp/conda/envs/Chat2BI/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/projects/Chat2BI/functions/retrieval/G1/corpus.tsv'
```

![image](https://github.com/mMrBun/Chat2BI/assets/57943407/1597aed4-d996-4c05-904c-81aaca943165)

**Comment by mMrBun** [comment]
#18

**Comment by pjcc5** [comment]
ok,Thanks♪(･ω･)ﾉ
